### ISSUE TITLE
Odd crash in cc65, related to delayed post-counting

### ISSUE THREAD

**Issue by mrdudz** [cc65/cc65#1438]
This one is really super odd. It happens when trying to compile this file:

https://github.com/EtchedPixels/FUZIX/blob/master/Applications/games/z1.c

apparently this worked at some point...

what happens is that it crashes with a segfault. apparently in the function CheckedSizeOf.

Now, i compiled cc65 with -O0 -g to track it down further... and the bug is gone... or different?. AAARGS

I know, its a terrible bug report. I tried reproducing it with a small code snippet but couldnt do it. Perhaps some array is overflowing? Some off by one error?

No idea how to proceed on this one

this is with pr #1435 merged locally, did not check yet if it is related

**Comment by oliverschmidt** [comment]
It would - of course - be great if you could identify which change brought that crash...

**Comment by mrdudz** [comment]
I will try :)

**Comment by acqn** [comment]
The cause is that the deferred post-inc/dec for `__fastcall__` function calls always tries to get the expression info for the last parameter that is supposed to be passed via AX/EAX even when there are no parameters. This is fixed by PR #1439.

**Comment by mrdudz** [comment]
It's still crashing here. The testcase looks like this:
```

/* Issue #1438 fix #1439 - crash in cc65, related to delayed post-counting 

  this is an odd issue, the compile would crash *sometimes*, perhaps in one
  of ten compilation runs.
*/

unsigned short __fastcall__ func2(void)
{
    return 42;
}

void func1(unsigned short *wp)
{
    *wp++ = func2();
}

int main(void)
{
    return 0;
}
```
For testing i use a makefile that has
```
cc65 -o foo bug1438.c
```
in it a few dozen times, it will crash randomly after a couple compilation runs

**Comment by mrdudz** [comment]
Doh. False alarm. Just git playing tricks on me again *shakes fist*
